name: Luftuj
version: 0.0.3-dev
slug: luftuj
description: Luftuj Home Assistant Add-on
url: https://github.com/luftuj-cz/home-assistant
arch:
  - aarch64
  - amd64
init: false
startup: services
homeassistant_api: true
host_network: true
hassio_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:fan
icon: icon.png
logo: logo.png
map:
  - share:rw
  - config:rw
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Frontend HTTP port
options:
  log_level: info
  web_port: 8099
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  web_port: int(1024,65535)
  mqtt_host: str?
  mqtt_port: int(1,65535)
  mqtt_user: str?
  mqtt_password: str?
image: "ghcr.io/luftuj-cz/{arch}-addon-luftuj"
