name: Luftuj
version: 0.1.0
slug: luftuj
description: Luftuj Home Assistant Add-on
url: https://github.com/luftuj-cz/home-assistant
arch:
  - armhf
  - aarch64
  - amd64
  - armv7
  - i386
init: false
startup: services
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:fan
icon: icon.png
logo: logo.png
map:
  - share:rw
  - config:rw
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Frontend HTTP port
options:
  log_level: info
  web_port: 8099
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  web_port: int(1024,65535)
  mqtt_host: str?
  mqtt_port: int(1,65535)
  mqtt_user: str?
  mqtt_password: str?
# TODO: Přidat až bude image existovat
#image: "ghcr.io/kankajm/{arch}-addon-luftujha"
